# Generated by Django 6.0 on 2025-12-18 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('duration', models.CharField(choices=[('1d', '1일'), ('3d', '3일'), ('7d', '7일'), ('30d', '1개월'), ('365d', '1년'), ('perm', '영구')], default='1d', max_length=10, verbose_name='정지 기간')),
                ('reason', models.TextField(blank=True, verbose_name='정지 사유')),
                ('banned_at', models.DateTimeField(auto_now_add=True, verbose_name='정지 시작')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='정지 만료')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('unbanned_at', models.DateTimeField(blank=True, null=True, verbose_name='정지 해제 시간')),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_issued', to=settings.AUTH_USER_MODEL, verbose_name='정지한 관리자')),
                ('unbanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_lifted', to=settings.AUTH_USER_MODEL, verbose_name='정지 해제한 관리자')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL, verbose_name='정지된 사용자')),
            ],
            options={
                'verbose_name': '정지',
                'verbose_name_plural': '정지 목록',
                'ordering': ['-banned_at'],
            },
        ),
    ]
