# Generated by Django 6.0 on 2026-01-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_userban'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_emoji',
            field=models.CharField(blank=True, default='', help_text='피크민 관련 이모지 (랭킹 등록 사용자만)', max_length=10, verbose_name='프로필 이모지'),
        ),
    ]
