# Generated by Django 6.0 on 2026-02-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='special_title',
            field=models.CharField(blank=True, choices=[('', '없음'), ('coordinator', '좌표 마스터'), ('explorer', '피크민 탐험가'), ('pioneer', '개척자'), ('legend', '전설의 대원'), ('supporter', '서포터')], default='', help_text='관리자가 부여하는 특별 칭호', max_length=20, verbose_name='특별 칭호'),
        ),
    ]
