# Generated by Django 6.0 on 2026-02-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_special_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_title',
            field=models.CharField(blank=True, choices=[('', '없음'), ('coordinator', '좌표 마스터'), ('explorer', '피크민 탐험가'), ('pioneer', '개척자'), ('legend', '전설의 대원'), ('supporter', '서포터')], default='', help_text='랭커가 직접 선택한 칭호 (1위: 모든 칭호, 2~3위: 일반 칭호만)', max_length=20, verbose_name='선택한 칭호'),
        ),
    ]
