# Generated by Django 6.0 on 2026-02-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_badge_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title_bg_color',
            field=models.CharField(blank=True, choices=[('', '기본'), ('red', '빨강'), ('orange', '주황'), ('yellow', '노랑'), ('green', '초록'), ('blue', '파랑'), ('purple', '보라'), ('pink', '분홍'), ('rainbow', '무지개')], default='', max_length=20, verbose_name='칭호 배경 색상'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='title_color',
            field=models.CharField(blank=True, choices=[('', '기본'), ('red', '빨강'), ('orange', '주황'), ('yellow', '노랑'), ('green', '초록'), ('blue', '파랑'), ('purple', '보라'), ('pink', '분홍'), ('rainbow', '무지개')], default='', max_length=20, verbose_name='칭호 글자 색상'),
        ),
    ]
