# Generated by Django 6.0 on 2026-02-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_title_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname_bg_color',
            field=models.CharField(blank=True, choices=[('', '기본'), ('red', '빨강'), ('orange', '주황'), ('yellow', '노랑'), ('green', '초록'), ('blue', '파랑'), ('purple', '보라'), ('pink', '분홍'), ('rainbow', '무지개')], default='', max_length=20, verbose_name='닉네임 배경 색상'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='badge_style',
            field=models.CharField(blank=True, choices=[('default', '기본'), ('background', '배경만'), ('glow', '글로우 효과'), ('underline', '홀로그램 언더라인')], default='default', help_text='닉네임 배지의 CSS 스타일', max_length=20, verbose_name='배지 스타일'),
        ),
    ]
