# Generated by Django 6.0 on 2026-02-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_nickname_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='text_stroke_strength',
            field=models.PositiveSmallIntegerField(default=0, help_text='0: 없음, 100: 최대 강도', verbose_name='텍스트 테두리 강도'),
        ),
    ]
