# Generated by Django 6.0 on 2026-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_text_stroke_strength'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='text_stroke_strength',
            new_name='text_stroke',
        ),
        migrations.AddField(
            model_name='customuser',
            name='text_shadow',
            field=models.PositiveSmallIntegerField(default=0, help_text='0: 없음, 100: 최대 강도', verbose_name='텍스트 그림자 강도'),
        ),
    ]
