# Generated by Django 6.0 on 2026-02-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_separate_stroke_shadow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='text_shadow',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='text_stroke',
        ),
    ]
