# Generated by Django 6.0 on 2026-02-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_text_stroke_shadow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exclusive_perks',
            field=models.CharField(blank=True, default='', help_text='전용 스타일/색상/칭호 코드 (쉼표 구분, 예: underline,rainbow,explorer)', max_length=200, verbose_name='전용 아이템'),
        ),
    ]
