# Generated by Django 6.0 on 2026-02-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_exclusive_perks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_valid_received',
        ),
    ]
