# Generated by Django 6.0 on 2025-12-14 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordinates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='coordinates.coordinate', verbose_name='좌표')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크들',
                'indexes': [models.Index(fields=['user', '-created_at'], name='interaction_user_id_02c4e6_idx')],
                'unique_together': {('user', 'coordinate')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='coordinates.coordinate', verbose_name='좌표')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '좋아요',
                'verbose_name_plural': '좋아요들',
                'indexes': [models.Index(fields=['user', 'coordinate'], name='interaction_user_id_f8b72b_idx'), models.Index(fields=['coordinate', '-created_at'], name='interaction_coordin_b8b5ac_idx')],
                'unique_together': {('user', 'coordinate')},
            },
        ),
        migrations.CreateModel(
            name='ValidityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('VALID', '지금도 됨'), ('INVALID', '이제 안 됨')], max_length=10, verbose_name='평가 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validity_feedbacks', to='coordinates.coordinate', verbose_name='좌표')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validity_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '유효성 평가',
                'verbose_name_plural': '유효성 평가들',
                'indexes': [models.Index(fields=['coordinate', 'feedback_type'], name='interaction_coordin_dbb82b_idx')],
                'unique_together': {('user', 'coordinate')},
            },
        ),
    ]
