# Generated by Django 6.0 on 2026-01-10 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0004_add_region'),
        ('interactions', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='coordinate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='coordinates.coordinate', verbose_name='좌표'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', '좋아요'), ('COMMENT', '댓글'), ('COPY_MILESTONE', '복사 마일스톤'), ('SUGGESTION_REPLY', '건의사항 답변')], max_length=20, verbose_name='알림 유형'),
        ),
    ]
