# Generated by Django 6.0 on 2026-01-17 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_photo_alter_comment_content'),
        ('interactions', '0003_alter_notification_coordinate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments.comment', verbose_name='댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '댓글 좋아요',
                'verbose_name_plural': '댓글 좋아요들',
                'indexes': [models.Index(fields=['user', 'comment'], name='interaction_user_id_e26e40_idx'), models.Index(fields=['comment', '-created_at'], name='interaction_comment_7dfc8f_idx')],
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
