# Generated by Django 6.0 on 2026-02-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_commentlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='validityfeedback',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='validityfeedback',
            name='interaction_coordin_dbb82b_idx',
        ),
        migrations.DeleteModel(
            name='ValidityFeedback',
        ),
    ]
