# Generated by Django 6.0 on 2025-12-14 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='경도')),
                ('location_name', models.CharField(blank=True, max_length=200, verbose_name='장소명')),
                ('flower_type', models.CharField(blank=True, choices=[('red', '빨간 꽃'), ('yellow', '노란 꽃'), ('blue', '파란 꽃'), ('white', '흰 꽃'), ('pink', '분홍 꽃'), ('purple', '보라 꽃')], max_length=20, verbose_name='꽃 종류')),
                ('flower_count', models.PositiveIntegerField(default=0, verbose_name='심은 꽃 수')),
                ('image', models.ImageField(blank=True, null=True, upload_to='farming/journals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farming_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '농사 일지',
                'verbose_name_plural': '농사 일지',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='설명')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='위도')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='경도')),
                ('location_name', models.CharField(max_length=200, verbose_name='장소명')),
                ('flower_type', models.CharField(choices=[('red', '빨간 꽃'), ('yellow', '노란 꽃'), ('blue', '파란 꽃'), ('white', '흰 꽃'), ('pink', '분홍 꽃'), ('purple', '보라 꽃'), ('any', '아무 꽃이나')], default='any', max_length=20, verbose_name='필요한 꽃')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='마감 시간')),
                ('status', models.CharField(choices=[('open', '모집중'), ('in_progress', '진행중'), ('completed', '완료'), ('closed', '마감')], default='open', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farming_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '농사 요청',
                'verbose_name_plural': '농사 요청',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmingParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farming_participations', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='farming.farmingrequest')),
            ],
            options={
                'verbose_name': '농사 참여',
                'verbose_name_plural': '농사 참여',
                'ordering': ['-created_at'],
                'unique_together': {('request', 'participant')},
            },
        ),
    ]
