# Generated by Django 6.0 on 2025-12-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmingjournal',
            name='flower_type',
            field=models.CharField(blank=True, help_text='예: 빨간 꽃, 노란 꽃, 파란 꽃 등', max_length=50, verbose_name='꽃 종류'),
        ),
        migrations.AlterField(
            model_name='farmingrequest',
            name='flower_type',
            field=models.CharField(blank=True, default='', help_text='예: 빨간 꽃, 아무 꽃이나 등', max_length=50, verbose_name='필요한 꽃'),
        ),
    ]
