# Generated by Django 6.0 on 2025-12-15 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0002_alter_farmingjournal_flower_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmingjournal',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요 수'),
        ),
        migrations.CreateModel(
            name='FarmingJournalLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='farming.farmingjournal', verbose_name='농사 일지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farming_journal_likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '농사 일지 좋아요',
                'verbose_name_plural': '농사 일지 좋아요',
                'indexes': [models.Index(fields=['user', 'journal'], name='farming_far_user_id_444360_idx'), models.Index(fields=['journal', '-created_at'], name='farming_far_journal_ba4198_idx')],
                'unique_together': {('user', 'journal')},
            },
        ),
    ]
