# Generated by Django 6.0 on 2025-12-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_farmingjournal_like_count_farmingjournallike'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmingjournal',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='댓글 수'),
        ),
    ]
