# Generated by Django 6.0 on 2025-12-16 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0004_farmingjournal_comment_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmingjournal',
            name='guest_nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='게스트 닉네임'),
        ),
        migrations.AddField(
            model_name='farmingjournal',
            name='guest_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='게스트 비밀번호'),
        ),
        migrations.AddField(
            model_name='farmingrequest',
            name='guest_nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='게스트 닉네임'),
        ),
        migrations.AddField(
            model_name='farmingrequest',
            name='guest_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='게스트 비밀번호'),
        ),
        migrations.AlterField(
            model_name='farmingjournal',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farming_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmingrequest',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farming_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
