# Generated by Django 6.0 on 2025-12-14 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('ALL', '전체'), ('WEEKLY', '주간'), ('MONTHLY', '월간')], max_length=10, verbose_name='기간 유형')),
                ('period_start', models.DateField(help_text='해당 기간의 시작 날짜', verbose_name='기간 시작일')),
                ('approved_posts_count', models.PositiveIntegerField(default=0, verbose_name='승인된 글 수')),
                ('likes_received_count', models.PositiveIntegerField(default=0, verbose_name='받은 좋아요 수')),
                ('valid_received_count', models.PositiveIntegerField(default=0, verbose_name='받은 VALID 수')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='총 점수')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='순위')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '랭킹',
                'verbose_name_plural': '랭킹들',
                'ordering': ['period_type', 'rank'],
                'indexes': [models.Index(fields=['period_type', 'period_start', 'rank'], name='rankings_ra_period__2c847f_idx'), models.Index(fields=['period_type', 'period_start', '-score'], name='rankings_ra_period__d7c459_idx')],
                'unique_together': {('user', 'period_type', 'period_start')},
            },
        ),
    ]
