# Generated by Django 6.0 on 2025-12-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='farming_likes_received_count',
            field=models.PositiveIntegerField(default=0, verbose_name='농사 일지 좋아요 수'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='invalid_received_count',
            field=models.PositiveIntegerField(default=0, verbose_name='받은 INVALID 수'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='score',
            field=models.IntegerField(default=0, verbose_name='총 점수'),
        ),
    ]
