# Generated by Django 6.0 on 2026-01-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_ranking_farming_likes_received_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='copy_received_count',
            field=models.PositiveIntegerField(default=0, verbose_name='받은 복사 수'),
        ),
    ]
