# Generated by Django 6.0 on 2026-02-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_ranking_copy_received_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='invalid_received_count',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='valid_received_count',
        ),
    ]
