# Generated by Django 6.0 on 2026-01-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('coordinates_list', '좌표 목록 페이지'), ('landing', '메인 페이지'), ('farming_list', '농사 일지 페이지')], max_length=50, unique=True, verbose_name='표시 위치')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '사이트 공지',
                'verbose_name_plural': '사이트 공지',
            },
        ),
    ]
