# Generated by Django 6.0 on 2026-01-08 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_nickname', models.CharField(blank=True, max_length=50, verbose_name='닉네임(비회원)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일(선택)')),
                ('category', models.CharField(choices=[('BUG', '버그 신고'), ('FEATURE', '기능 제안'), ('QUESTION', '문의'), ('OTHER', '기타')], default='OTHER', max_length=20, verbose_name='분류')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('REVIEWED', '검토완료'), ('RESOLVED', '처리완료')], default='PENDING', max_length=20, verbose_name='상태')),
                ('admin_note', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '건의사항',
                'verbose_name_plural': '건의사항',
                'ordering': ['-created_at'],
            },
        ),
    ]
