# Generated by Django 6.0 on 2026-01-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranker_limit_exempt_rank', models.PositiveIntegerField(default=10, help_text='전체 랭킹에서 이 순위 이내의 유저는 일일 업로드 제한이 없습니다. (0 = 비활성화)', verbose_name='랭커 제한 해제 순위')),
                ('daily_upload_limit', models.PositiveIntegerField(default=3, help_text='카테고리별 하루 업로드 제한 (0 = 무제한)', verbose_name='일일 업로드 제한')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '사이트 설정',
                'verbose_name_plural': '사이트 설정',
            },
        ),
        migrations.AddField(
            model_name='suggestion',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='사용자에게 표시되는 공식 답변', verbose_name='관리자 답변'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='답변일'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='admin_note',
            field=models.TextField(blank=True, help_text='내부용 메모 (사용자에게 보이지 않음)', verbose_name='관리자 메모'),
        ),
    ]
