# Generated by Django 6.0 on 2026-02-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_suggestion_admin_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenotice',
            name='update_log',
            field=models.TextField(blank=True, help_text='사이트 업데이트 내역', verbose_name='업데이트 내역'),
        ),
        migrations.AlterField(
            model_name='sitenotice',
            name='content',
            field=models.TextField(help_text='사이트 공지 내용', verbose_name='내용'),
        ),
    ]
