# Generated by Django 6.0 on 2025-12-14 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordinates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='내용')),
                ('guest_nickname', models.CharField(blank=True, max_length=30, verbose_name='비회원 닉네임')),
                ('guest_password', models.CharField(blank=True, max_length=128, verbose_name='비회원 비밀번호')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제됨')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coordinates.coordinate', verbose_name='좌표')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment', verbose_name='부모 댓글')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글들',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['coordinate', 'created_at'], name='comments_co_coordin_e7b898_idx'), models.Index(fields=['parent'], name='comments_co_parent__fdf1ec_idx')],
            },
        ),
    ]
