# Generated by Django 6.0 on 2025-12-15 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('coordinates', '0001_initial'),
        ('farming', '0004_farmingjournal_comment_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='farming_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='farming.farmingjournal', verbose_name='농사 일지'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='coordinate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coordinates.coordinate', verbose_name='좌표'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['farming_journal', 'created_at'], name='comments_co_farming_041ba3_idx'),
        ),
    ]
