# Generated by Django 6.0 on 2026-01-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_farming_journal_alter_comment_coordinate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, help_text='댓글에 첨부할 사진 (최대 5MB, JPG/PNG/WEBP)', null=True, upload_to='comment_photos/%Y/%m/%d/', verbose_name='사진'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=500, verbose_name='내용'),
        ),
    ]
