# Generated by Django 6.0 on 2026-02-11 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=50)),
                ('source_language', models.CharField(max_length=5)),
                ('target_language', models.CharField(max_length=5)),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '콘텐츠 번역',
                'verbose_name_plural': '콘텐츠 번역',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='translation_content_d4cdf1_idx')],
                'unique_together': {('content_type', 'object_id', 'field_name', 'target_language')},
            },
        ),
    ]
