# Generated by Django 6.0 on 2025-12-14 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('coordinates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', '스팸/광고'), ('WRONG_INFO', '잘못된 정보'), ('INAPPROPRIATE', '부적절한 내용'), ('OTHER', '기타')], max_length=20, verbose_name='신고 사유')),
                ('detail', models.TextField(blank=True, max_length=500, verbose_name='상세 내용')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('RESOLVED', '처리됨'), ('DISMISSED', '기각')], default='PENDING', max_length=20, verbose_name='처리 상태')),
                ('admin_note', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고일')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment', verbose_name='댓글')),
                ('coordinate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='coordinates.coordinate', verbose_name='좌표')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
            ],
            options={
                'verbose_name': '신고',
                'verbose_name_plural': '신고들',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='reports_rep_status_7dd5e5_idx')],
            },
        ),
    ]
