# Generated by Django 6.0 on 2025-12-14 04:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='위도')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='경도')),
                ('category', models.CharField(choices=[('MUSHROOM', '버섯'), ('BIGFLOWER', '빅플라워'), ('SEEDLING', '모종'), ('OTHER', '기타')], default='OTHER', max_length=20, verbose_name='카테고리')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인'), ('REJECTED', '거절')], default='PENDING', max_length=20, verbose_name='상태')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
                ('bookmark_count', models.PositiveIntegerField(default=0, verbose_name='북마크 수')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='댓글 수')),
                ('valid_count', models.PositiveIntegerField(default=0, verbose_name='유효 평가 수')),
                ('invalid_count', models.PositiveIntegerField(default=0, verbose_name='무효 평가 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 검증일')),
                ('guest_password', models.CharField(blank=True, help_text='비회원이 글 수정/삭제 시 사용', max_length=128, verbose_name='비회원 비밀번호')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinates', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '좌표',
                'verbose_name_plural': '좌표들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoordinateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coordinates/%Y/%m/', verbose_name='이미지')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coordinates.coordinate', verbose_name='좌표')),
            ],
            options={
                'verbose_name': '좌표 이미지',
                'verbose_name_plural': '좌표 이미지들',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coordinate',
            index=models.Index(fields=['status', '-created_at'], name='coordinates_status_b83b37_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinate',
            index=models.Index(fields=['category', 'status'], name='coordinates_categor_53b6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinate',
            index=models.Index(fields=['-like_count'], name='coordinates_like_co_01eae0_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinate',
            index=models.Index(fields=['-valid_count'], name='coordinates_valid_c_5ae324_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinate',
            index=models.Index(fields=['author', 'status'], name='coordinates_author__ccbe13_idx'),
        ),
    ]
