# Generated by Django 6.0 on 2025-12-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='postcard_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='엽서이름'),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
