# Generated by Django 6.0 on 2025-12-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0002_coordinate_postcard_name_coordinate_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='copy_count',
            field=models.PositiveIntegerField(default=0, verbose_name='복사 수'),
        ),
    ]
