# Generated by Django 6.0 on 2025-12-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0003_add_copy_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='region',
            field=models.CharField(blank=True, choices=[('KOREA', '한국 🇰🇷'), ('JAPAN', '일본 🇯🇵'), ('NORTH_AMERICA', '북미 🌎'), ('EUROPE', '유럽 🇪🇺'), ('ASIA_OTHER', '아시아 🌏'), ('OTHER', '기타 🌍')], default='OTHER', max_length=20, verbose_name='지역'),
        ),
    ]
