# Generated by Django 6.0 on 2026-02-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0004_add_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='watermark_enabled',
            field=models.BooleanField(default=False, help_text='사진에 닉네임 워터마크 표시', verbose_name='워터마크 표시'),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='watermark_name',
            field=models.CharField(blank=True, help_text='워터마크에 표시될 이름 (비어있으면 작성자 닉네임 사용)', max_length=50, verbose_name='워터마크 닉네임'),
        ),
    ]
