# Generated by Django 6.0 on 2026-02-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0005_coordinate_watermark_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coordinate',
            name='coordinates_valid_c_5ae324_idx',
        ),
        migrations.RemoveField(
            model_name='coordinate',
            name='invalid_count',
        ),
        migrations.RemoveField(
            model_name='coordinate',
            name='last_verified_at',
        ),
        migrations.RemoveField(
            model_name='coordinate',
            name='valid_count',
        ),
    ]
